### ISSUE TITLE
fails to complete sometimes in sublime

### ISSUE THREAD

**Issue by Roger-luo** [jakeconnor/JuliaCompletions#2]
it fails to complete sometimes when I use sublime to type julia

**Comment by jakeconnor** [comment]
This isn't a useful statement of the issue. Before I can even start to look into it, I'll need an example of when this occurs, including answers to the following.

Can this be reliably reproduced, and if so how? 
Does it always happen for a certain keyword? Sometimes for only a certain word? Sometimes for many words?

For an example word, what do you do to make the issue occur? What do you expect to happen? What actually happens?

**Comment by Roger-luo** [comment]
Sorry for the unclear issue

It fails to complete when I type Unicode by words like \phi when it's not in the last line. if type things like \phi in the last line of the whole code text, it works just fine.

**Comment by utkinis** [comment]
This happens due to #1, if `keyword.operator.arithmetic.julia` is removed, everything works (except effect of #1, of course).

**Comment by Roger-luo** [comment]
Thanks,it works!
